on:
 push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Build with Gradle
        run: |
          ./gradlew check buildPlugin
      - name: Releases Upload
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/distributions/Tapd-Vcs-*.zip

