on:
 push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - master
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Build with Gradle
        run: |
          ./gradlew check buildPlugin
      - name: Archive distribution artifact
        uses: actions/upload-artifact@v3
        with:
          name: "tapd-vcs-intellij-development"
          path: build/distributions/Tapd-Vcs-*.zip
